export enum Actions {
    SET_INPUT = "SET_INPUT",
    SET_SUGGESTIONS = "SET_SUGGESTIONS",
    CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS",
    SET_SELECTED = "SET_SELECTED",
    REMOVE_SELECTED = "REMOVE_SELECTED",
}
