export enum Actions {
    SET_INPUT = "SET_INPUT",
    SET_SUGGESTIONS = "SET_SUGGESTIONS",
    CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS",
    SET_SELECTED = "SET_SELECTED",
    REMOVE_SELECTED = "REMOVE_SELECTED",
    SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS",
    SET_SELECTED_RECIPE = "SET_SELECTED_RECIPE",
    SET_DETAILED_RECIPE = "SET_DETAILED_RECIPE",
    SET_RANDOM_RESULTS = "SET_RANDOM_RESULTS",
}
