export enum Actions {
    SET_INPUT = "SET_INPUT",
    SET_SUGGESTIONS = "SET_SUGGESTIONS",
    CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS",
    SET_SELECTED = "SET_SELECTED",
    CLEAR_SELECTED = "CLEAR_SELECTED",
    REMOVE_SELECTED = "REMOVE_SELECTED",
    SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS",
    SET_RECIPE = "SET_RECIPE",
    SET_RANDOM_RESULTS = "SET_RANDOM_RESULTS",
    SET_LOADING = "SET_LOADING",
    SET_IS_RANDOM = "SET_IS_RANDOM",
    SET_RANDOM_COUNT = "SET_RANDOM_COUNT",
}
